### ISSUE TITLE
MFCLogger not working; giving out errors.

### ISSUE THREAD

**Issue by Syl0pt** [ZombieAlex/MFCLogger#4] opened 2019-06-27 19:54 UTC
For the last few days i've been not able to use MFClogger and getting errors like this:

load.js:1
var serverConfig = <html>
                   ^

SyntaxError: Unexpected token <
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInContext (vm.js:284:10)
    at Function.compiler (/home/user/node_modules/load/index.js:56:6)
    at Client.<anonymous> (/home/user/node_modules/MFCAuto/lib/Client.js:395:26)
    at Generator.next (<anonymous>)
    at fulfilled (/home/user/node_modules/MFCAuto/lib/Client.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
load.js:1
var serverConfig = <html>
                   ^

Trying it with test.js I get: 
$ node test.js
(node:18033) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token <
(node:18033) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18033) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I'm hoping to get this fixed ASAP, but I don't know javascript.

**Comment by ZombieAlex** [comment] 2019-06-28 06:44
On startup by default, MFCAuto tries to load the MFC server config from this url: https://www.myfreecams.com/_js/serverconfig.js

The contents should be a single JavaScript object literal, but for you it appears to start with a &lt; character. That likely means the url is serving you a web page instead of the expected JS. Are you behind a proxy perhaps? If so, the proxy may have changed behavior on you. Can you share the contents of that url as loaded from your machine?

If you're on a relatively recent MFCAuto, one option to avoid that url load completely is to initialize the client object you're using to log as so:

`const client = new mfc.Client("guest", "guest", {useCachedServerConfig: true});`

I can't reproduce any MFCLogger issues here. I have an instance running 24/7 and test.js is working for me as well.

**Comment by Syl0pt** [comment] 2019-06-29 06:36
Sorry it took this long to respond, busier day than i expected.
I'm not behind a proxy, but i have had MFCLogger running on PM2 for about a year now with very few problems until this one. But I highly doubt it has anything to do with that since I get the same error when running it the regular way i.e. $ node chat.js

I have MFCAuto_v5.11.3. but not sure if that's the version the logger is running on or not as i have a few MFCauto's on my PC (Linux Mint 18.1 xfce). I'm not sure how to check to see which mfcauto the logger is running off of.

As for the: const client = new mfc.Client("guest", "guest", {useCachedServerConfig: true});
I have no idea what to do with that or where I would put it. Some help would be useful if you don't mind. 

If I try installing the MFCauto version I have and then the MFClogger will it mess anything up, node-wise? My mfc-node is still working fine for recording shows, i'd hate to mess that up trying to fix this.

**Comment by mordacthepreventor** [comment] 2019-06-29 16:14
same problem here.  
on windows 10 build 1809
all of a sudden after no problem forever about 2 weeks ago.

I've uninstalled k9 (a form of proxy) and rebooted.  no other proxy.  still fails.

here is the serverconfig.js as downloaded using chrome. let me know if there was a 'cleaner' way to download it.

will try setting usecachedserveconfig to true later today and post an update.  just wanted to weight in so you know its not only one guy having the problem.  

[serverconfig.js.txt](https://github.com/ZombieAlex/MFCLogger/files/3342073/serverconfig.js.txt)

**Comment by mordacthepreventor** [comment] 2019-06-30 02:08
have not yet figured out where to set useCachedServerConfig: true successfully. (which would just be a band-aide anyway and would break next time mfc changes servers)

trying to find the cause of the breakage:
using wireshark, I see GET for /_js/serverconfig.js occuring on TCP 80.
the server responds with a 301 redirecting to a 443/TCP (HTTPS) page.  (pasted below)
that redirect includes html code.  I think that is the greater than sign that the javascript is erroring on.

Does anyone know where to make sure the request for serverconfig.js occurs over https in the first place?
I haven't found it yet.  The only place I can fine IS using https already.  

I'll try not to spam the thread too much as I continue working.   
```
    <html>\r\n
    <head><title>301 Moved Permanently</title></head>\r\n
    <body bgcolor="white">\r\n
    <center><h1>301 Moved Permanently</h1></center>\r\n
    <hr><center>nginx</center>\r\n
    </body>\r\n
    </html>\r\n
```

**Comment by ZombieAlex** [comment] 2019-06-30 02:34
Thanks mordac. I'm still not entirely sure what to tell either of you. MFCAuto has been purely HTTPS for quite a while now. The only reference to the serverconfig.js url is in client.js.

Is it possible you have multiple versions of MFCAuto?  5.11.3 wouldn't have the problem as I currently understand it, which is that the request for serverconfig.js is expecting purely JS and receiving HTML (perhaps that redirect page you mention mordac).

MFCLogger is a library that does nothing by itself. It needs to be part of a larger program. Since you're having trouble finding where the client is initialized, I gather that you're both running it within a separate program you got from somewhere else? Can you point me to that code?

**Comment by mordacthepreventor** [comment] 2019-06-30 04:33
> Is it possible you have multiple versions of MFCAuto?

thats it!   

It appears that my mfclogger is using mfcauto version 3.4.6.
I thought I was using mfcauto 5.2.0 which i have in other directories.

> I gather that you're both running it within a separate program you got from somewhere else?

my mfclogger and mfcauto are both directly from you / this page. 

I was unaware of the fork with 5.11.  Found it with a google just now. I have installed that, and am now back working.   I bet 5.2 would even have worked if I'd installed it right in the first place.   

thanks so much for your help, and also for writing it in the first place.  I've been using it for over 2 years.   glad to have it working again.   I'm sorry that i took up your time with something that was my fault.

**Comment by ZombieAlex** [comment] 2019-06-30 05:32
No worries. Glad you got it sorted and glad you've found the code useful. I appreciate the kind words.

3.4.6 is a very old version indeed. I'm surprised it lasted this long.  As of this comment, 5.11.5 is the latest MFCAuto version but anything from 5.11.3 up should work fine for most purposes.

@Syl0pt I suspect you have multiple copies of MFCAuto installed too. Check for nested "MFCAuto" directories under your MFCLogger install especially. The fix for you is likely as simple as deleting the older duplicate folder.

**Comment by Syl0pt** [comment] 2019-06-30 05:59
Honestly I have no idea how many MFCAuto's i have installed or exactly where they would all be located. I'm not savvy at any of this stuff at all. I haven't been able to follow most of what you fellas have been talking about here. lol. It's all gibberish to me. So I think the best thing for me to do would be to delete all the mfcauto's I have (hopefully I can find them all, eventually) and just install the latest mfcauto, but I have no idea where to find it. The last version of it i got was from the Learn2Record volafile page a few months back, i think. https://volafile.org/r/nJioNv. If you could provide a link to the latest version I'd appreciate it as I have no idea where to go to find it. I tried googling "MFCAuto v5.11.5" but got no results back. ShitTot@gmail.com is my email address if you don't want to link it here since it was DMCA'd on github. Sincere apologies for my total noobness.

**Comment by ZombieAlex** [comment] 2019-06-30 06:37
This link will expire after 1 day or 5 downloads, whichever comes first, after which I'll delete this comment.

https://send.firefox.com/download/87d7fecd13c411df/#N6Ob4weQZ2vfP5GIKpVLVw

Though I question whether you'll even be able to install it given your knowledge level.

In either case, this isn't a bug with the MFCLogger package. So I'm closing this issue.

**Closed as completed by ZombieAlex** 2019-06-30 06:37 UTC

**Comment by Syl0pt** [comment] 2019-06-30 06:43
Thanks, I appreciate it, but i'm not seeing any kind of link. It's just blank. Screenshot here: https://imgur.com/a/AHzh2zY
